[package]
name = "stama"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonpath-rust = "0.7.2"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"

[features]
threaded = []
